version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - BACKEND_PORT=3001
      - CORS_ORIGIN=https://localhost:3000
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - mcr-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=https://localhost:3001
      - NEXT_PUBLIC_WS_URL=wss://localhost:3001
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - mcr-network

  ndi-bridge:
    build:
      context: ./ndi-bridge
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - NDI_BRIDGE_PORT=8000
      - NDI_BRIDGE_HOST=0.0.0.0
      - BACKEND_URL=https://backend:3001
      - BACKEND_WS_URL=wss://backend:3001
      - NDI_SOURCE_PREFIX=MobileCam
      - MAX_STREAMS=10
      - PROCESSING_QUALITY=high
    volumes:
      - ./ndi-bridge:/app
      - ./output:/app/output  # For MPEG-TS files
    networks:
      - mcr-network
    depends_on:
      - backend

networks:
  mcr-network:
    driver: bridge

volumes:
  output:
    driver: local