services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ../infra/docker/Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://192.168.100.16:3001
      - NEXT_PUBLIC_WS_URL=ws://192.168.100.16:3001
    command: npm run dev
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: ../infra/docker/Dockerfile.backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - BACKEND_PORT=3001
      - CORS_ORIGIN=http://192.168.100.16:3000
    command: npm run dev

  ndi-bridge:
    build:
      context: ./ndi-bridge
      dockerfile: ../infra/docker/Dockerfile.ndi-bridge
    ports:
      - "8000:8000"
    volumes:
      - ./ndi-bridge:/app
    network_mode: host
    environment:
      - PYTHONUNBUFFERED=1
      - NDI_BRIDGE_PORT=8000
      - BACKEND_URL=http://192.168.100.16:3001
      - NDI_SOURCE_PREFIX=MobileCam
    command: python3 src/main.py
    depends_on:
      - backend

