version: '3.8'

services:
  test-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - BACKEND_PORT=3001
      - CORS_ORIGIN=https://localhost:3000
    command: ["node", "-e", "console.log('Backend container is working!'); process.exit(0)"]

  test-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=https://localhost:3001
      - NEXT_PUBLIC_WS_URL=wss://localhost:3001
    command: ["node", "-e", "console.log('Frontend container is working!'); process.exit(0)"]

  test-ndi-bridge:
    build:
      context: ./ndi-bridge
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - NDI_BRIDGE_PORT=8000
      - NDI_BRIDGE_HOST=0.0.0.0
    command: ["python", "-c", "print('NDI Bridge container is working!'); exit(0)"]
