version: '3.8'

services:
  backend-simple:
    build:
      context: ./backend
      dockerfile: Dockerfile.simple
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - BACKEND_PORT=3001
      - CORS_ORIGIN=https://localhost:3000
    # command: ["node", "-e", "console.log('✅ Backend container is working!'); setInterval(() => console.log('Backend running...'), 5000)"]

  frontend-simple:
    build:
      context: ./frontend
      dockerfile: Dockerfile.simple
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=https://localhost:3001
      - NEXT_PUBLIC_WS_URL=wss://localhost:3001
    # command: ["node", "-e", "console.log('✅ Frontend container is working!'); setInterval(() => console.log('Frontend running...'), 5000)"]

  ndi-bridge-simple:
    build:
      context: ./ndi-bridge
      dockerfile: Dockerfile.simple
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - NDI_BRIDGE_PORT=8000
      - NDI_BRIDGE_HOST=0.0.0.0
    # command: ["python", "-c", "print('✅ NDI Bridge container is working!'); import time; [print(f'NDI Bridge running... {i}') or time.sleep(5) for i in range(100)]"]
